-- ============================================================
-- Unique constraints, foreign keys, and column defaults
-- (applied AFTER data load so historical data can't violate them)
-- ============================================================

-- ── Unique constraints ──────────────────────────
-- Unique constraints (auto-converted)
ALTER TABLE "AttendanceLogs" ADD CONSTRAINT "UQ_AttendanceLogs_EmpId_AttendanceDate" UNIQUE ("EmpId", "AttendanceDate");
ALTER TABLE "Departments" ADD CONSTRAINT "UQ_Departments_DeptName" UNIQUE ("DeptName");
ALTER TABLE "Designations" ADD CONSTRAINT "UQ_Designations_DesigName" UNIQUE ("DesigName");
ALTER TABLE "Employees" ADD CONSTRAINT "UQ_Employees_EmpCode" UNIQUE ("EmpCode");
ALTER TABLE "Employees" ADD CONSTRAINT "UQ_Employees_Email" UNIQUE ("Email");
ALTER TABLE "Invoices" ADD CONSTRAINT "UQ_Invoices_InvoiceNumber" UNIQUE ("InvoiceNumber");
ALTER TABLE "Modules" ADD CONSTRAINT "UQ_Modules_ModuleCode" UNIQUE ("ModuleCode");
ALTER TABLE "PayrollRuns" ADD CONSTRAINT "UQ_PayrollRuns_EmpId_Month_Year" UNIQUE ("EmpId", "Month", "Year");
ALTER TABLE "PurchaseOrders" ADD CONSTRAINT "UQ_PurchaseOrders_PoNumber" UNIQUE ("PoNumber");
ALTER TABLE "RoleEntitlements" ADD CONSTRAINT "UQ_RoleEntitlements_RoleId_ScreenId" UNIQUE ("RoleId", "ScreenId");
ALTER TABLE "Roles" ADD CONSTRAINT "UQ_Roles_RoleName" UNIQUE ("RoleName");
ALTER TABLE "Screens" ADD CONSTRAINT "UQ_Screens_ScreenCode" UNIQUE ("ScreenCode");
ALTER TABLE "StockLevels" ADD CONSTRAINT "UQ_StockLevels_ProductId" UNIQUE ("ProductId");
ALTER TABLE "UserEntitlements" ADD CONSTRAINT "UQ_UserEntitlements_UserScreen" UNIQUE ("UserId", "ScreenId");
ALTER TABLE "Users" ADD CONSTRAINT "UQ_Users_Username" UNIQUE ("Username");
ALTER TABLE "Users" ADD CONSTRAINT "UQ_Users_Email" UNIQUE ("Email");

-- ── Foreign keys ─────────────────────────────────
-- Foreign keys (auto-converted)
ALTER TABLE "AttendanceLogs" ADD CONSTRAINT "FK_AttendanceLogs_EmpId" FOREIGN KEY ("EmpId") REFERENCES "Employees" ("EmpId");
ALTER TABLE "CrmActivities" ADD CONSTRAINT "FK_CrmActivities_ClientId" FOREIGN KEY ("ClientId") REFERENCES "Clients" ("ClientId");
ALTER TABLE "CrmActivities" ADD CONSTRAINT "FK_CrmActivities_LeadId" FOREIGN KEY ("LeadId") REFERENCES "Leads" ("LeadId");
ALTER TABLE "Employees" ADD CONSTRAINT "FK_Employees_DeptId" FOREIGN KEY ("DeptId") REFERENCES "Departments" ("DeptId");
ALTER TABLE "Employees" ADD CONSTRAINT "FK_Employees_DesigId" FOREIGN KEY ("DesigId") REFERENCES "Designations" ("DesigId");
ALTER TABLE "Employees" ADD CONSTRAINT "FK_Employees_ReportingManagerId" FOREIGN KEY ("ReportingManagerId") REFERENCES "Employees" ("EmpId");
ALTER TABLE "Followups" ADD CONSTRAINT "FK_Followups_LeadId" FOREIGN KEY ("LeadId") REFERENCES "Leads" ("LeadId");
ALTER TABLE "InvoiceItems" ADD CONSTRAINT "FK_InvoiceItems_InvoiceId" FOREIGN KEY ("InvoiceId") REFERENCES "Invoices" ("InvoiceId");
ALTER TABLE "InvoiceItems" ADD CONSTRAINT "FK_InvoiceItems_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("ProductId");
ALTER TABLE "Invoices" ADD CONSTRAINT "FK_Invoices_ClientId" FOREIGN KEY ("ClientId") REFERENCES "Clients" ("ClientId");
ALTER TABLE "Leads" ADD CONSTRAINT "FK_Leads_AssignedToId" FOREIGN KEY ("AssignedToId") REFERENCES "Users" ("UserId");
ALTER TABLE "Leads" ADD CONSTRAINT "FK_Leads_ConvertedToClientId" FOREIGN KEY ("ConvertedToClientId") REFERENCES "Clients" ("ClientId");
ALTER TABLE "PayrollRuns" ADD CONSTRAINT "FK_PayrollRuns_EmpId" FOREIGN KEY ("EmpId") REFERENCES "Employees" ("EmpId");
ALTER TABLE "PurchaseOrderItems" ADD CONSTRAINT "FK_PurchaseOrderItems_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("ProductId");
ALTER TABLE "PurchaseOrderItems" ADD CONSTRAINT "FK_PurchaseOrderItems_PoId" FOREIGN KEY ("PoId") REFERENCES "PurchaseOrders" ("PoId");
ALTER TABLE "PurchaseOrders" ADD CONSTRAINT "FK_PurchaseOrders_VendorId" FOREIGN KEY ("VendorId") REFERENCES "Vendors" ("VendorId");
ALTER TABLE "RoleEntitlements" ADD CONSTRAINT "FK_RoleEntitlements_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("RoleId");
ALTER TABLE "RoleEntitlements" ADD CONSTRAINT "FK_RoleEntitlements_ScreenId" FOREIGN KEY ("ScreenId") REFERENCES "Screens" ("ScreenId");
ALTER TABLE "Screens" ADD CONSTRAINT "FK_Screens_ModuleId" FOREIGN KEY ("ModuleId") REFERENCES "Modules" ("ModuleId");
ALTER TABLE "StockLevels" ADD CONSTRAINT "FK_StockLevels_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("ProductId");
ALTER TABLE "StockMovements" ADD CONSTRAINT "FK_StockMovements_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("ProductId");
ALTER TABLE "UserEntitlements" ADD CONSTRAINT "FK_UserEntitlements_Screens" FOREIGN KEY ("ScreenId") REFERENCES "Screens" ("ScreenId") ON DELETE CASCADE;
ALTER TABLE "UserEntitlements" ADD CONSTRAINT "FK_UserEntitlements_Users" FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId") ON DELETE CASCADE;
ALTER TABLE "Users" ADD CONSTRAINT "FK_Users_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("RoleId");

-- ── Column defaults ──────────────────────────────
-- Column defaults (auto-converted)
ALTER TABLE "AttendanceLogs" ALTER COLUMN "DurationMinutes" SET DEFAULT 0;
ALTER TABLE "AttendanceLogs" ALTER COLUMN "Source" SET DEFAULT 'MANUAL';
ALTER TABLE "AttendanceLogs" ALTER COLUMN "CreatedAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Clients" ALTER COLUMN "IsActive" SET DEFAULT TRUE;
ALTER TABLE "Clients" ALTER COLUMN "CreatedAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Clients" ALTER COLUMN "IsDeleted" SET DEFAULT FALSE;
ALTER TABLE "Companies" ALTER COLUMN "CompanyType" SET DEFAULT 'CORPORATE';
ALTER TABLE "Companies" ALTER COLUMN "Currency" SET DEFAULT 'INR';
ALTER TABLE "Companies" ALTER COLUMN "IsActive" SET DEFAULT TRUE;
ALTER TABLE "Companies" ALTER COLUMN "CreatedAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "CrmActivities" ALTER COLUMN "Status" SET DEFAULT 'OPEN';
ALTER TABLE "CrmActivities" ALTER COLUMN "CreatedAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "CrmActivities" ALTER COLUMN "IsDeleted" SET DEFAULT FALSE;
ALTER TABLE "Departments" ALTER COLUMN "IsActive" SET DEFAULT TRUE;
ALTER TABLE "Departments" ALTER COLUMN "IsDeleted" SET DEFAULT FALSE;
ALTER TABLE "Departments" ALTER COLUMN "CreatedAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Designations" ALTER COLUMN "Level" SET DEFAULT 1;
ALTER TABLE "Designations" ALTER COLUMN "IsActive" SET DEFAULT TRUE;
ALTER TABLE "Employees" ALTER COLUMN "EmploymentType" SET DEFAULT 'FULL_TIME';
ALTER TABLE "Employees" ALTER COLUMN "Status" SET DEFAULT 'ACTIVE';
ALTER TABLE "Employees" ALTER COLUMN "BasicSalary" SET DEFAULT 0;
ALTER TABLE "Employees" ALTER COLUMN "CreatedAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Employees" ALTER COLUMN "IsDeleted" SET DEFAULT FALSE;
ALTER TABLE "Followups" ALTER COLUMN "FollowupType" SET DEFAULT 'CALL';
ALTER TABLE "Followups" ALTER COLUMN "Status" SET DEFAULT 'PENDING';
ALTER TABLE "Followups" ALTER COLUMN "CreatedAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Followups" ALTER COLUMN "IsDeleted" SET DEFAULT FALSE;
ALTER TABLE "InvoiceItems" ALTER COLUMN "DiscountPct" SET DEFAULT 0;
ALTER TABLE "InvoiceItems" ALTER COLUMN "DiscountAmount" SET DEFAULT 0;
ALTER TABLE "InvoiceItems" ALTER COLUMN "TaxableAmount" SET DEFAULT 0;
ALTER TABLE "InvoiceItems" ALTER COLUMN "CgstRate" SET DEFAULT 0;
ALTER TABLE "InvoiceItems" ALTER COLUMN "CgstAmount" SET DEFAULT 0;
ALTER TABLE "InvoiceItems" ALTER COLUMN "SgstRate" SET DEFAULT 0;
ALTER TABLE "InvoiceItems" ALTER COLUMN "SgstAmount" SET DEFAULT 0;
ALTER TABLE "InvoiceItems" ALTER COLUMN "IgstRate" SET DEFAULT 0;
ALTER TABLE "InvoiceItems" ALTER COLUMN "IgstAmount" SET DEFAULT 0;
ALTER TABLE "InvoiceItems" ALTER COLUMN "TotalAmount" SET DEFAULT 0;
ALTER TABLE "InvoiceItems" ALTER COLUMN "SortOrder" SET DEFAULT 0;
ALTER TABLE "Invoices" ALTER COLUMN "Status" SET DEFAULT 'DRAFT';
ALTER TABLE "Invoices" ALTER COLUMN "PaymentStatus" SET DEFAULT 'UNPAID';
ALTER TABLE "Invoices" ALTER COLUMN "Subtotal" SET DEFAULT 0;
ALTER TABLE "Invoices" ALTER COLUMN "DiscountAmount" SET DEFAULT 0;
ALTER TABLE "Invoices" ALTER COLUMN "TaxableAmount" SET DEFAULT 0;
ALTER TABLE "Invoices" ALTER COLUMN "CgstTotal" SET DEFAULT 0;
ALTER TABLE "Invoices" ALTER COLUMN "SgstTotal" SET DEFAULT 0;
ALTER TABLE "Invoices" ALTER COLUMN "IgstTotal" SET DEFAULT 0;
ALTER TABLE "Invoices" ALTER COLUMN "TaxTotal" SET DEFAULT 0;
ALTER TABLE "Invoices" ALTER COLUMN "TdsPct" SET DEFAULT 0;
ALTER TABLE "Invoices" ALTER COLUMN "TdsAmount" SET DEFAULT 0;
ALTER TABLE "Invoices" ALTER COLUMN "RoundOff" SET DEFAULT 0;
ALTER TABLE "Invoices" ALTER COLUMN "GrandTotal" SET DEFAULT 0;
ALTER TABLE "Invoices" ALTER COLUMN "PaidAmount" SET DEFAULT 0;
ALTER TABLE "Invoices" ALTER COLUMN "BalanceAmount" SET DEFAULT 0;
ALTER TABLE "Invoices" ALTER COLUMN "IsInterstate" SET DEFAULT FALSE;
ALTER TABLE "Invoices" ALTER COLUMN "CreatedAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Invoices" ALTER COLUMN "IsDeleted" SET DEFAULT FALSE;
ALTER TABLE "InvoiceSequence" ALTER COLUMN "NextNum" SET DEFAULT 1;
ALTER TABLE "Leads" ALTER COLUMN "Status" SET DEFAULT 'NEW';
ALTER TABLE "Leads" ALTER COLUMN "Priority" SET DEFAULT 'MEDIUM';
ALTER TABLE "Leads" ALTER COLUMN "ExpectedValue" SET DEFAULT 0;
ALTER TABLE "Leads" ALTER COLUMN "CreatedAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Leads" ALTER COLUMN "IsDeleted" SET DEFAULT FALSE;
ALTER TABLE "Modules" ALTER COLUMN "SortOrder" SET DEFAULT 0;
ALTER TABLE "Modules" ALTER COLUMN "IsActive" SET DEFAULT TRUE;
ALTER TABLE "PayrollRuns" ALTER COLUMN "DaysWorked" SET DEFAULT 0;
ALTER TABLE "PayrollRuns" ALTER COLUMN "LopDays" SET DEFAULT 0;
ALTER TABLE "PayrollRuns" ALTER COLUMN "GrossSalary" SET DEFAULT 0;
ALTER TABLE "PayrollRuns" ALTER COLUMN "TotalDeductions" SET DEFAULT 0;
ALTER TABLE "PayrollRuns" ALTER COLUMN "NetSalary" SET DEFAULT 0;
ALTER TABLE "PayrollRuns" ALTER COLUMN "PfEmployee" SET DEFAULT 0;
ALTER TABLE "PayrollRuns" ALTER COLUMN "PfEmployer" SET DEFAULT 0;
ALTER TABLE "PayrollRuns" ALTER COLUMN "EsiEmployee" SET DEFAULT 0;
ALTER TABLE "PayrollRuns" ALTER COLUMN "EsiEmployer" SET DEFAULT 0;
ALTER TABLE "PayrollRuns" ALTER COLUMN "TdsAmount" SET DEFAULT 0;
ALTER TABLE "PayrollRuns" ALTER COLUMN "ProfessionalTax" SET DEFAULT 0;
ALTER TABLE "PayrollRuns" ALTER COLUMN "Status" SET DEFAULT 'DRAFT';
ALTER TABLE "PayrollRuns" ALTER COLUMN "CreatedAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "PoSequence" ALTER COLUMN "NextNum" SET DEFAULT 1;
ALTER TABLE "Products" ALTER COLUMN "ProductType" SET DEFAULT 'GOODS';
ALTER TABLE "Products" ALTER COLUMN "Unit" SET DEFAULT 'PCS';
ALTER TABLE "Products" ALTER COLUMN "TaxRate" SET DEFAULT 0;
ALTER TABLE "Products" ALTER COLUMN "PurchasePrice" SET DEFAULT 0;
ALTER TABLE "Products" ALTER COLUMN "SalePrice" SET DEFAULT 0;
ALTER TABLE "Products" ALTER COLUMN "IsActive" SET DEFAULT TRUE;
ALTER TABLE "Products" ALTER COLUMN "CreatedAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Products" ALTER COLUMN "IsDeleted" SET DEFAULT FALSE;
ALTER TABLE "PurchaseOrders" ALTER COLUMN "Status" SET DEFAULT 'DRAFT';
ALTER TABLE "PurchaseOrders" ALTER COLUMN "TotalAmount" SET DEFAULT 0;
ALTER TABLE "PurchaseOrders" ALTER COLUMN "CreatedAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "PurchaseOrders" ALTER COLUMN "IsDeleted" SET DEFAULT FALSE;
ALTER TABLE "RoleEntitlements" ALTER COLUMN "CanCreate" SET DEFAULT FALSE;
ALTER TABLE "RoleEntitlements" ALTER COLUMN "CanRead" SET DEFAULT FALSE;
ALTER TABLE "RoleEntitlements" ALTER COLUMN "CanUpdate" SET DEFAULT FALSE;
ALTER TABLE "RoleEntitlements" ALTER COLUMN "CanDelete" SET DEFAULT FALSE;
ALTER TABLE "Roles" ALTER COLUMN "IsActive" SET DEFAULT TRUE;
ALTER TABLE "Roles" ALTER COLUMN "CreatedAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Screens" ALTER COLUMN "SortOrder" SET DEFAULT 0;
ALTER TABLE "StockLevels" ALTER COLUMN "WarehouseName" SET DEFAULT 'Main Warehouse';
ALTER TABLE "StockLevels" ALTER COLUMN "OpeningStock" SET DEFAULT 0;
ALTER TABLE "StockLevels" ALTER COLUMN "CurrentStock" SET DEFAULT 0;
ALTER TABLE "StockLevels" ALTER COLUMN "ReservedStock" SET DEFAULT 0;
ALTER TABLE "StockLevels" ALTER COLUMN "ReorderLevel" SET DEFAULT 0;
ALTER TABLE "StockLevels" ALTER COLUMN "LastUpdated" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "StockMovements" ALTER COLUMN "CreatedAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "UserEntitlements" ALTER COLUMN "CanCreate" SET DEFAULT FALSE;
ALTER TABLE "UserEntitlements" ALTER COLUMN "CanRead" SET DEFAULT TRUE;
ALTER TABLE "UserEntitlements" ALTER COLUMN "CanUpdate" SET DEFAULT FALSE;
ALTER TABLE "UserEntitlements" ALTER COLUMN "CanDelete" SET DEFAULT FALSE;
ALTER TABLE "UserEntitlements" ALTER COLUMN "CreatedAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Users" ALTER COLUMN "IsActive" SET DEFAULT TRUE;
ALTER TABLE "Users" ALTER COLUMN "CreatedAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Vendors" ALTER COLUMN "IsActive" SET DEFAULT TRUE;
ALTER TABLE "Vendors" ALTER COLUMN "CreatedAt" SET DEFAULT CURRENT_TIMESTAMP;
